"""initial_schema

Revision ID: fa616d2f83a2
Revises: None
Create Date: 2026-06-18 13:54:01.682315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa616d2f83a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_constraints',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('subject_tag', sa.String(length=200), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('object_tag', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation IN ('requires', 'excludes', 'prefers', 'avoids')", name='ck_constraints_relation_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_tag', 'relation', 'object_tag', name='uq_constraints_subject_relation_object')
    )
    op.create_index('ix_constraints_object_tag', 'component_constraints', ['object_tag'], unique=False)
    op.create_index('ix_constraints_relation', 'component_constraints', ['relation'], unique=False)
    op.create_index('ix_constraints_subject_tag', 'component_constraints', ['subject_tag'], unique=False)
    op.create_table('component_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stories',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False, comment="'standalone' or 'continuation'"),
    sa.Column('status', sa.String(length=30), nullable=False, comment="'pending', 'planning', 'writing', 'reviewing', 'complete', 'failed'"),
    sa.Column('generation_seed', sa.String(length=200), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('target_word_count', sa.Integer(), nullable=False),
    sa.Column('actual_word_count', sa.Integer(), nullable=True),
    sa.Column('parent_story_id', sa.UUID(), nullable=True),
    sa.Column('story_bible', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True, comment='Stored as ISO string or timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_mode', 'stories', ['mode'], unique=False)
    op.create_index('ix_stories_parent_story_id', 'stories', ['parent_story_id'], unique=False)
    op.create_index('ix_stories_status', 'stories', ['status'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('component_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prompt_fragment', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('compatibility_tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('rarity_weight', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_components_compatibility_tags_gin', 'components', ['compatibility_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_components_component_type_id', 'components', ['component_type_id'], unique=False)
    op.create_index('ix_components_is_active', 'components', ['is_active'], unique=False)
    op.create_index('ix_components_slug', 'components', ['slug'], unique=False)
    op.create_index('ix_components_tags_gin', 'components', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('story_chapters',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('outline', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment="'pending', 'writing', 'reviewing', 'complete', 'failed'"),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('canon_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'chapter_number', name='uq_chapters_story_number')
    )
    op.create_index('ix_chapters_story_id', 'story_chapters', ['story_id'], unique=False)
    op.create_table('story_component_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False, comment='e.g. protagonist, antagonist, primary_setting, main_activity'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'component_id', 'role', name='uq_links_story_component_role')
    )
    op.create_index('ix_links_component_id', 'story_component_links', ['component_id'], unique=False)
    op.create_index('ix_links_story_id', 'story_component_links', ['story_id'], unique=False)
    op.create_table('story_scenes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('beat', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment="'pending', 'writing', 'complete', 'failed'"),
    sa.Column('continuity_notes', sa.Text(), nullable=True),
    sa.Column('wordsmith_notes', sa.Text(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['story_chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'scene_number', name='uq_scenes_chapter_number')
    )
    op.create_index('ix_scenes_chapter_id', 'story_scenes', ['chapter_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment="'planner', 'scene_writer', 'continuity', 'judge', 'wordsmith', 'sampler'"),
    sa.Column('status', sa.String(length=30), nullable=False, comment="'running', 'complete', 'failed', 'retried'"),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['story_scenes.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_agent_name', 'agent_runs', ['agent_name'], unique=False)
    op.create_index('ix_agent_runs_scene_id', 'agent_runs', ['scene_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_index('ix_agent_runs_story_id', 'agent_runs', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_runs_story_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_scene_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_agent_name', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_scenes_chapter_id', table_name='story_scenes')
    op.drop_table('story_scenes')
    op.drop_index('ix_links_story_id', table_name='story_component_links')
    op.drop_index('ix_links_component_id', table_name='story_component_links')
    op.drop_table('story_component_links')
    op.drop_index('ix_chapters_story_id', table_name='story_chapters')
    op.drop_table('story_chapters')
    op.drop_index('ix_components_tags_gin', table_name='components', postgresql_using='gin')
    op.drop_index('ix_components_slug', table_name='components')
    op.drop_index('ix_components_is_active', table_name='components')
    op.drop_index('ix_components_component_type_id', table_name='components')
    op.drop_index('ix_components_compatibility_tags_gin', table_name='components', postgresql_using='gin')
    op.drop_table('components')
    op.drop_index('ix_stories_status', table_name='stories')
    op.drop_index('ix_stories_parent_story_id', table_name='stories')
    op.drop_index('ix_stories_mode', table_name='stories')
    op.drop_table('stories')
    op.drop_table('component_types')
    op.drop_index('ix_constraints_subject_tag', table_name='component_constraints')
    op.drop_index('ix_constraints_relation', table_name='component_constraints')
    op.drop_index('ix_constraints_object_tag', table_name='component_constraints')
    op.drop_table('component_constraints')
    # ### end Alembic commands ###